### ISSUE TITLE
如果视频的描述是markdown的内容， 则根据markdown进行转换

### ISSUE THREAD

**Issue by xiongbo** [Techbay/readss#12]
如题

**Comment by xiongbo** [comment]
视频文件的描述在网站上按照markdown的格式进行展示， 需要用到markdown的convert gem， 测试方面要编写view和单元测试

**Comment by ohliumliu** [comment]
@xiongbo 这个“描述”是指的从网站上通过api拿到的description么？还是用户自己写的summary。是从markdown转到html给view展示么。

**Comment by xiongbo** [comment]
@ohliumliu

如果我没记错的话， 就是description， 然后转成html

**Comment by ohliumliu** [comment]
是从youtube或者vimeo上下来的description么，这个看着不像markdown
'Hello' is taken from the new album, 25, out November 20. http://adele.com Available now from iTunes http://smarturl.it/itunes25 Available now from Amazon
好像media的description是plain text
http://stackoverflow.com/questions/16504232/formatting-embedded-youtube-video-descriptions
还没找到官方api的说法。

**Comment by xiongbo** [comment]
@ohliumliu  如果不是markdown的内容， 就可以直接输出， 我指的是我们自己上传的视频 ，会采用markdown的形式， 对视频中的内容进行解释或者描述， 这个时候， 就需要这个功能了

**Comment by ohliumliu** [comment]
好的，我尽快做一下。根据这篇文章 http://www.sitepoint.com/markdown-processing-ruby/
是不是redcarpet作为首选，功能最全而且最快。

2016-05-04 7:48 GMT-07:00 ian <notifications@github.com>:
