### ISSUE TITLE
添加admin管理功能

### ISSUE THREAD

**Issue by xiongbo** [Techbay/readss#20]
使用https://github.com/thoughtbot/administrate 作为后台的管理平台

**Comment by ohliumliu** [comment]
官方administrate现在暂不支持rails 5，用了一个非官方的
gem 'administrate', github: 'hayesr/administrate', branch: 'rails5_compat'

相关讨论 https://github.com/thoughtbot/administrate/issues/404

**Comment by ohliumliu** [comment]
增加log out 按钮, 在search右边

**Comment by ohliumliu** [comment]
还没找到在administrate的search box旁边加log out button的办法。
现在有两个手段：
1 把layouts/_header.html.erb加到search box上边，但是这样的话header的最右边的内容就没有了（可是html里面有。
1 改动administrate的index.html.erb，加上一个logout button。但还是不能加在search box右边。

**Comment by xiongbo** [comment]
加不上是因为css的原因吗？
