### ISSUE TITLE
修正mobile视图下的登录问题

### ISSUE THREAD

**Issue by xiongbo** [Techbay/readss#23]
<img width="826" alt="screen shot 2016-05-12 at 09 43 51" src="https://cloud.githubusercontent.com/assets/1317465/15201696/36b276a2-1826-11e6-9a9c-553560fb9cf7.png">

mobile视图下看不到用户登录和注册的按钮

**Comment by ohliumliu** [comment]
4a2a862db9eaa879549f6221fff42435c925234f
刚改了一下，和administrate那个问题相关。
