### ISSUE TITLE
视频管理测试 videos_controller_test

### ISSUE THREAD

**Issue by ohliumliu** [Techbay/readss#25]
问题：
1. 这是integration test还是controller test
1.  现在是按照integration test 处理， 需要mock用户登录。因为测试环境的用户来自于fixture，所以yml文件中不能提前设置用户（password是加密的并且masked）。需要在set up里面通过post新建一个用户。

**Comment by ohliumliu** [comment]
原来这还是个很活跃的问题
https://github.com/plataformatec/devise/issues/3913
我的理解是：rails 5把controller test自动做成了integration test，但是devise还没有跟上这个变化。上面那个issue里面最后决定做个新的helper。

**Comment by ohliumliu** [comment]
Following the suggestion in the link above to add a sign_in helper. A more elegant way of using warden is not implemented.

**Comment by xiongbo** [comment]
cool!
