### ISSUE TITLE
实现视频自动抓取功能

### ISSUE THREAD

**Issue by xiongbo** [Techbay/readss#8]
当有新的视频传到特定的栏目或者频道下， 可以自动进行抓取

**Comment by xiongbo** [comment]
使用DelayJob作为后端的任务系统， 自动抓取视频列表中的视频， 并保存到数据库中。

**Comment by ohliumliu** [comment]
videos_controller_test.rb现在是个integration test，好像devise的helper只能在controller test里面用。
https://groups.google.com/forum/#!topic/plataformatec-devise/aLSxHCc7aqE
那该怎么mock sign in呢
